### ISSUE TITLE
React router (3.0.2) only showing white screen with no errors.

### ISSUE THREAD

**Issue by KjetilVaa** [ReactjsProgram/Redux-Immutable#9]
I have followed the tutorials - My code: 

<img width="573" alt="screen shot 2017-03-13 at 23 14 25" src="https://cloud.githubusercontent.com/assets/17502961/23877500/e4c09a78-0842-11e7-972b-7604838096bc.png">
<img width="482" alt="screen shot 2017-03-13 at 23 14 36" src="https://cloud.githubusercontent.com/assets/17502961/23877498/e471ba5c-0842-11e7-9657-96dc5cfe9b32.png">
<img width="522" alt="screen shot 2017-03-13 at 23 14 44" src="https://cloud.githubusercontent.com/assets/17502961/23877499/e47226cc-0842-11e7-84ab-1ff4d4875310.png">

In my browser it seems that I get some form of a router-id:
<img width="258" alt="screen shot 2017-03-13 at 23 16 16" src="https://cloud.githubusercontent.com/assets/17502961/23877568/32eab486-0843-11e7-89e4-bf0da7bed36e.png">

**Comment by stefanodem** [comment]
The issue is with hashHistory. It's been moved to a new package, 'react-router-dom'. [https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/api/HashRouter.md](url)

So you can either change to the new module. This worked for me: 
![screen shot 2017-07-23 at 14 41 48](https://user-images.githubusercontent.com/11004671/28499404-3c535602-6fb5-11e7-9179-fb8bba555da4.png)


Or just install the older 'react-router' module which still has the hashHistory module via `npm install --save react-router@2.0.1`

**Comment by tylermcginnis** [comment]
RRV4 is completely new, so you can't expect to upgrade and have your code still work. The Redux course will be getting a router update in the next 1-2 weeks.
